### ISSUE TITLE
How to set multiple Validation on one View?

### ISSUE THREAD

**Issue by slee8789** [WesleyElliott/Kubwa#12]
How to set multiple Validation on one View?

< example >
**@Password(errorMessage = R.string.password_error, scheme = PasswordRule.Scheme.ALPHA_MIXED_CASE)**
@NotNull.List({
        **@NotNull(name = "passwordNotNull", errorMessage = R.string.errortest1),**
        @NotNull(name = "confirmPasswordNotNull", errorMessage = R.string.errortest2)
})

<EditText
            android:id="@+id/join_pw"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginEnd="@dimen/default_40"
            android:layout_marginStart="@dimen/default_40"
            android:hint="@string/ui_login_psw_hint"
            android:inputType="textPassword"
            android:text="@{viewModel.userPassword}"
            **app:error="@{viewModel.passwordErrorMessage}"
            app:error="@{viewModel.passwordNotNullMessage}"**
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/join_id" />

**Comment by WesleyElliott** [comment]
Hi,

Please post a snippet of the ViewModel code, specifically how the generated Validator is used

**Comment by slee8789** [comment]
I want to apply multi validation check for edittext, but app:error attribute can only use one

    @Password(errorMessage = R.string.password_error, scheme = PasswordRule.Scheme.ALPHA_MIXED_CASE)
    @ConfirmPassword(errorMessage = R.string.confirm_password_error)
    public class ViewModel {
    ...
        public String getPasswordErrorMessage() {
            return validator.getPasswordErrorMessage();
        }
        public String getConfirmPasswordErrorMessage() {
            return validator.getConfirmPasswordErrorMessage();
        }
    }


    <EditText
            android:id="@+id/join_pw"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginEnd="@dimen/default_40"
            android:layout_marginStart="@dimen/default_40"
            android:hint="@string/ui_login_psw_hint"
            android:inputType="textPassword"
            android:maxLines="1"
            android:text="@{viewModel.userPassword}"
            app:error="@{viewModel.passwordErrorMessage}"
            app:error="@{viewModel.passwordNotNullErrorMessage}"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/join_id" />

**Comment by WesleyElliott** [comment]
Thanks. Thats a limitation of the EditText, not something this library attempts to solve. Each EditText can only have one error, even without using this library.
Best option would be to have one ViewModel method for returning the correct error message:

ViewModel:
```
public String getPasswordError() {
    if (validator.getPasswordErrorMessage() != null) {
        return validator.getPasswordErrorMessage();
    }  else if (validator.getPasswordNotNullMessage() != null) {
        return validator.getPasswordNotNullMessage();
    }

    return null;
} 
```

XML:
```
<EditText
        android:id="@+id/join_pw"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginEnd="@dimen/default_40"
        android:layout_marginStart="@dimen/default_40"
        android:hint="@string/ui_login_psw_hint"
        android:inputType="textPassword"
        android:maxLines="1"
        android:text="@{viewModel.userPassword}"
        app:error="@{viewModel.passwordError}"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/join_id" />
````

That way, the View only has one error message based on multiple error messages for provided by the validator.

I'm going to close this issue as its not related to the library.

**Comment by slee8789** [comment]
Thanks!!
