### ISSUE TITLE
Attribute value must be constant

### ISSUE THREAD

**Issue by russosanti** [WesleyElliott/Kubwa#14]
Hi,
When following your instructions and setting i.e.

    @Password(errorMessage = R.string.password_error, scheme = PasswordRule.Scheme.ANY)

R.string.password_error results in: Error. Attribute value must be constant

**Comment by WesleyElliott** [comment]
Hi,

Could you provide more info? AS and gradle version, kotlin or java, androidX or not, and perhaps a snippet of your actual code?

Only thing I can think of is you'r providing a variable for `errorMessage` that isn't defined as a constant
