### ISSUE TITLE
Problem when usecase: one rule for multiple fields

### ISSUE THREAD

**Issue by KhoaSuperman** [WesleyElliott/Kubwa#4]
Hi, thanks for great library

I have problem with the case First Name and Last Name are individual field and cannot be null.
My ViewModel:

@NotNull(errorMessage = R.string.error_name)
public class UserProfile_ViewModel extends BaseObservable

...

    //validator
    public String getFirstNameError() {
        return validator.getNotNullErrorMessage();
    }

    public String getLastNameError() {
        return validator.getNotNullErrorMessage();
    }

Let say, first name is empty but the error message was showed on both fields first name and lastname.

Do you have any ideas for this situation ? Tks

**Comment by WesleyElliott** [comment]
Hi @KhoaSuperman ,

If you have multiple validations of the same type (in this case, @NonNull), you need to set it up like this:

```
@NotNull.List({
        @NotNull(name = "firstNameError", errorMessage = R.string.error_name),
        @NotNull(name = "lastNameError", errorMessage = R.string.error_last_name)
})
```

Note the `name="firstNameError"` - this is so you have a reference when getting the error:

```
public String getFirstNameError() {
    return validator.getFirstNameError(); // name = "firstNameError"
}

public String getLastNameError() {
    return validator.getLastNameError(); // name = "lastNameError"
}
```

I hope this helps? If not, see the [Wiki](https://github.com/WesleyElliott/Kubwa/wiki), specifically the [Lists](https://github.com/WesleyElliott/Kubwa/wiki/Lists) section

**Comment by KhoaSuperman** [comment]
Thank you so much. it works (y)

**Comment by WesleyElliott** [comment]
Pleasure :) Enjoy!
