### ISSUE TITLE
"app:error" Not Working

### ISSUE THREAD

**Issue by pichardoJ** [WesleyElliott/Kubwa#6]
When trying to follow the example found this error.

[http://stackoverflow.com/questions/41068826/android-data-binding-edittext-seterror](url)

**Comment by WesleyElliott** [comment]
As posted on StackOverflow:
This is more a question on how to use the Data Binding library. You're binding errorText to the error, but in the layout you use error. Changing the BindingAdapter to @BindingAdapter({"app:error"}) should fix the error

**Comment by pichardoSoftware** [comment]
Shouldn't this adapter be part of the library? And no, it doesn't :(

**Comment by WesleyElliott** [comment]
Sorry for the late reply. You technically shouldn't need the `@BindingAdapter` anyway, `app:error` should work by default. 

Maybe post your ViewModel code?
