### ISSUE TITLE
How to use duplicate annotations on Model?

### ISSUE THREAD

**Issue by xrnd** [WesleyElliott/Kubwa#7]
e.g I have form with few fields as optional. Since rest of the fields are strings but Compulsory. I am trying to put @NotNull annotation for each but I get duplicate annotation now allowed error.

**Comment by WesleyElliott** [comment]
Hi - I see the Wiki entry on this may not stand out as much as it should :) Check the [Lists](https://github.com/WesleyElliott/Kubwa/wiki/Lists) section of the Wiki for using multiple validations with the same type. Essentially, you'll use the `@NotNull.List` annotation:

```
@NotNull.List({
    @NotNull(name = "streetError", errorMessage = R.string.streetError),
    @NotNull(name = "cityError", errorMessage = R.string.cityError),
    @NotNull(name = "countryError", errorMessage = R.string.countryError)
})
```

The `.List` annotations are available for all validation annotations.

**Comment by xrnd** [comment]
Hi @WesleyElliott, yes thats what I was looking for. Thanks. 
Now, the name attribute with Annotation is optional, but I added for my annotations in the list.
I have also associated my xml widget with same name and made one error getter for the same. 
But it keeps giving 

ERROR
"Error: Cannot find the setter for attribute 'app:checkedBySelectError' with parameter type java.lang.String on com.companyname.CustomUI.myspinnergen.MySearchableSpinner. "

My annotations look like this   ANNOTATIONS CODE
`@NotNull.List({
        @NotNull(name = "ownerSelectError",errorMessage = R.string.validation_owner_selection),
        @NotNull(name = "numberSelectError",errorMessage = R.string.validation_number_selection),
        @NotNull(name = "checkedBySelectError",errorMessage = R.string.validation_user_selection)
})`

XML CODE

` <com.companyname.CustomUI.myspinnergen.MySearchableSpinner
                        android:id="@+id/checkedBy"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        app:checkedBySelectError="@{viewmodel.checkedBySelectError}"
                        app:adapter="@{qualityCheckAdapter}"
                        bind:selectedCheckedBy="@={viewmodel.CheckUserName}"/>`

GETTER CODE IN VIEW MODEL

` public String getCheckedBySelectError() {return getCheckedBySelectError();}`

It did create Validation Class for my VM, until xml code everything looked fine, but as soon as i added error property to spinner something went wrong.
I have done all checks mentioned, am i missing any ? pl suggest.

**Comment by WesleyElliott** [comment]
Hi,

Its hard to see whats wrong without seeing more code unfortunately.
It looks like its a data-binding issue though, have you checked that you have a `@BindingAdapter` for `app:checkedBySelectError`?

If you remove the `app:checkedBySelectError` from the xml, does everything compile? If so, the problem lies with your data binding setup, and not with Kubwa.

**Comment by xrnd** [comment]
Hi,

I understand that you will need to see the whole code. I have added the @BindingAdapter I have used for that widget. But do I need one for "app:checkedBySelectError"? 
Since I have added my own name to the annotation? as from the wiki I realised the need of getter but not sure of creating @BindingAdaptor too.
 
Also to add, when I remove  app:checkedBySelectError, it gives same error with other widget in not null annotation. So I eventually removed all properties from xml and with only VM code the project compiled well.

**Comment by WesleyElliott** [comment]
Ok, if it compiles without your custom attributes then you've done something wrong in the data binding part. Looking at your BindingAdapter, I can't see a BindingAdapter setup for `checkedBySelectError`? If you want any custom bindings, you need to specify them with a BindingAdapter (thats required by the Data Binding library and isn't a Kubwa thing - Kubwa only provides the error message as a string, how you bind it is still up to you).

**Comment by xrnd** [comment]
Hi @WesleyElliott 
Got it. I will try and add that @BindingAdaptor code for Error Attribute.
